version: '3'
services:
  code:
    container_name: multiprocess_container
    build: ../code
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"